apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-k8s-salesaccount-deployment
  labels:
    app: docker-k8s-salesaccount
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: docker-k8s-salesaccount
  template:
    metadata:
      labels:
        app: docker-k8s-salesaccount
    spec:
      containers:
      - name: docker-k8s-salesaccount
        image: saijayant/salesaccount
        ports:
        - containerPort: 8080    
        
      
