FROM java:8

EXPOSE 8080

ADD build/libs/SeventhProjectBootWithDocker-0.0.1-SNAPSHOT.jar SeventhProjectBootWithDocker-0.0.1-SNAPSHOT.jar

ENTRYPOINT ["java","-jar","SeventhProjectBootWithDocker-0.0.1-SNAPSHOT.jar"]